'use client'
import {FormEvent,useState} from 'react'
import {useRouter} from 'next/navigation'
import Link from 'next/link'
import {ArrowLeft} from 'lucide-react'
import {supabase} from '../../../lib/supabase'
import SessionGate from '../../components/SessionGate'
export default function PostWin(){const router=useRouter();const [f,setF]=useState({title:'',event_name:'',achievement:'',description:'',category:'',achievement_date:'',proof_url:''});const [msg,setMsg]=useState('');async function submit(e:FormEvent){e.preventDefault();const {data:{user}}=await supabase.auth.getUser();if(!user)return;const {error}=await supabase.from('wins').insert({...f,user_id:user.id,achievement_date:f.achievement_date||null});if(error)setMsg(error.message);else router.push('/wins')}return <SessionGate role="student"><div className="form-wide"><Link href="/wins" className="back"><ArrowLeft size={16}/> My wins</Link><div className="top"><div><div className="eyebrow">Achievement</div><div className="title">Post a win</div><div className="sub">Submit proof and the management team can verify it for your portfolio.</div></div></div><form className="card form-card" onSubmit={submit}><div className="form-grid"><Field label="Win title *" value={f.title} set={v=>setF({...f,title:v})}/><Field label="Event / organisation *" value={f.event_name} set={v=>setF({...f,event_name:v})}/><Field label="Achievement *" value={f.achievement} set={v=>setF({...f,achievement:v})}/><Field label="Category" value={f.category} set={v=>setF({...f,category:v})}/><Field label="Achievement date" type="date" value={f.achievement_date} set={v=>setF({...f,achievement_date:v})}/><Field label="Proof URL" type="url" value={f.proof_url} set={v=>setF({...f,proof_url:v})}/></div><div className="field"><label>Description</label><textarea value={f.description} onChange={e=>setF({...f,description:e.target.value})}/></div><button className="btn">Submit for verification</button>{msg&&<div className="flash">{msg}</div>}</form></div></SessionGate>}
function Field({label,value,set,type='text'}:any){return <div className="field"><label>{label}</label><input required={label.includes('*')} type={type} value={value} onChange={e=>set(e.target.value)}/></div>}
