'use client'
import {useEffect,useMemo,useState} from 'react'
import Link from 'next/link'
import {CalendarClock,ExternalLink,Filter,CheckCircle2} from 'lucide-react'
import {supabase} from '../../lib/supabase'
import SessionGate from '../components/SessionGate'
const statuses=['all','saved','applied','shortlisted','interview','selected','rejected','withdrawn']
export default function Applications(){const [rows,setRows]=useState<any[]>([]);const [filter,setFilter]=useState('all');const [loading,setLoading]=useState(true);async function load(){const {data:{user}}=await supabase.auth.getUser();if(!user)return;const {data}=await supabase.from('applications').select('*,opportunities(id,title,organization,type,deadline,application_url)').eq('user_id',user.id).order('updated_at',{ascending:false});setRows(data||[]);setLoading(false)}useEffect(()=>{load()},[]);const visible=useMemo(()=>filter==='all'?rows:rows.filter(x=>x.status===filter),[rows,filter]);return <SessionGate role="student"><div className="top"><div><div className="eyebrow">Your progress</div><div className="title">Application Tracker</div><div className="sub">One place for every application, deadline and next step.</div></div><Link className="btn" href="/opportunities">+ Find opportunity</Link></div><div className="tracker-grid">{statuses.slice(1).map(s=><div className="mini-stat" key={s}><b>{rows.filter(r=>r.status===s).length}</b><span>{s}</span></div>)}</div><div className="filter-line"><Filter size={15}/>{statuses.map(s=><button key={s} className={`filter-pill ${filter===s?'active':''}`} onClick={()=>setFilter(s)}>{s}</button>)}</div>{loading?<div className="loading-card">Loading your applications…</div>:visible.length?<div className="application-list">{visible.map((r:any)=><ApplicationRow key={r.id} row={r} refresh={load}/>)}</div>:<div className="card empty-state"><b>No applications here</b><span>Start from the opportunities page and track your progress with one click.</span></div>}</SessionGate>}
function ApplicationRow({row,refresh}:{row:any;refresh:()=>void}){const [status,setStatus]=useState(row.status);async function update(v:string){const {error}=await supabase.from('applications').update({status:v,updated_at:new Date().toISOString()}).eq('id',row.id);if(!error){setStatus(v);refresh()}}const deadline=row.opportunities?.deadline;const days=deadline?Math.ceil((new Date(deadline).getTime()-Date.now())/86400000):null;return <div className="card application-row"><div className="app-main"><span className="tag">{row.opportunities?.type}</span><Link href={`/opportunities/${row.opportunities?.id}`}><h3>{row.opportunities?.title}</h3></Link><span className="org">{row.opportunities?.organization}</span></div><div className="app-deadline"><CalendarClock size={16}/><div><b>{deadline?days!==null&&days>=0?`${days} days left`:'Deadline passed':'No deadline'}</b><span>{deadline?new Date(deadline).toLocaleString():'Not specified'}</span></div></div><select value={status} onChange={e=>update(e.target.value)}><option value="saved">Saved</option><option value="applied">Applied</option><option value="shortlisted">Shortlisted</option><option value="interview">Interview</option><option value="selected">Selected</option><option value="rejected">Rejected</option><option value="withdrawn">Withdrawn</option></select>{row.opportunities?.application_url&&<a className="icon-link" href={row.opportunities.application_url} target="_blank" rel="noreferrer"><ExternalLink size={16}/></a>}</div>}
