'use client'
import Link from 'next/link'
import {useEffect,useState} from 'react'
import {ArrowUpRight,CalendarClock,ChevronRight,Clock3,Target,Trophy,Plus} from 'lucide-react'
import {supabase} from '../lib/supabase'
import SessionGate from './components/SessionGate'
import OpportunityCard from './components/OpportunityCard'
export default function Home(){const [profile,setProfile]=useState<any>();const [opps,setOpps]=useState<any[]>([]);const [apps,setApps]=useState<any[]>([]);const [saved,setSaved]=useState(0);useEffect(()=>{(async()=>{const {data:{user}}=await supabase.auth.getUser();if(!user)return;const [{data:p},{data:o},{data:a},{count}]=await Promise.all([supabase.from('profiles').select('*').eq('id',user.id).single(),supabase.from('opportunities').select('*').eq('status','published').order('deadline',{ascending:true}).limit(3),supabase.from('applications').select('*,opportunities(title,deadline,organization)',{count:'exact'}).eq('user_id',user.id).order('updated_at',{ascending:false}).limit(5),supabase.from('saved_opportunities').select('*',{count:'exact',head:true}).eq('user_id',user.id)]);setProfile(p);setOpps(o||[]);setApps(a||[]);setSaved(count||0)})()},[]);return <SessionGate role="student"><div className="top"><div><div className="eyebrow">Student workspace</div><div className="title">Welcome back{profile?.full_name?`, ${profile.full_name.split(' ')[0]}`:''}.</div><div className="sub">Your opportunities, applications and wins, in one place.</div></div><Link className="btn" href="/opportunities">Explore opportunities <ArrowUpRight size={16}/></Link></div><section className="hero card"><div><span className="eyebrow inverse">SNUC TECH SOCIETY</span><h1>Don’t miss the opportunity that changes your next semester.</h1><p>Discover hackathons, internships, fellowships and competitions curated for the SNUC community.</p></div><div className="hero-actions"><Link className="btn light" href="/opportunities">Explore now <ArrowUpRight size={15}/></Link><Link className="hero-link" href="/applications">Track applications</Link></div></section><div className="stats-grid"><Stat icon={Target} value={String(opps.length)} label="Live opportunities"/><Stat icon={Clock3} value={String(apps.length)} label="Tracked applications"/><Stat icon={CalendarClock} value={String(saved)} label="Saved for later"/><Stat icon={Trophy} value="My wins" label="Build your portfolio" href="/wins"/></div><div className="section-title"><h2>Closing soon</h2><Link href="/opportunities">View all <ChevronRight size={15}/></Link></div><div className="opps">{opps.length?opps.map(x=><OpportunityCard key={x.id} item={x}/>):<Empty title="No live opportunities yet" text="Management can publish the first one from the management portal."/>}</div><div className="section-title"><h2>Application pulse</h2><Link href="/applications">Open tracker <ChevronRight size={15}/></Link></div><div className="card list">{apps.length?apps.map((a:any)=><div className="row" key={a.id}><div><b>{a.opportunities?.title}</b><span className="sub">{a.opportunities?.organization||'Opportunity'}</span></div><span className="status">{a.status}</span></div>):<Empty title="Your tracker is empty" text="Open an opportunity and hit Apply now to start tracking it."/>}</div></SessionGate>}
function Stat({icon:I,value,label,href}:any){const body=<><I size={19}/><b>{value}</b><span>{label}</span></>;return href?<Link href={href} className="stat-card">{body}</Link>:<div className="stat-card">{body}</div>}function Empty({title,text}:any){return <div className="empty-state"><b>{title}</b><span>{text}</span></div>}
